site_name: OpenSemanticLab Python Package (osl)
site_url: https://OpenSemanticLab.github.io/Tools/

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        options:
          docstring_style: numpy


nav:
    - Home: index.md
    - tools.md
    - osl.md
    - model.md

theme:
  name: "material"
